In [1]:
import torch
import numpy as np
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [2]:
a=torch.arange(1,21)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [3]:
a=a.reshape(4,5)
a

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [4]:
a.ndim

2

In [5]:
a.shape

torch.Size([4, 5])

In [6]:
a.size()

torch.Size([4, 5])

In [7]:
a[0]

tensor([1, 2, 3, 4, 5])

In [8]:
a

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [9]:
a.shape

torch.Size([4, 5])

In [10]:
a.squeeze()

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [11]:
a.shape

torch.Size([4, 5])

In [12]:
a=a.reshape(1,20)

In [13]:
a=a.unsqueeze(dim=0)
a

tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
          18, 19, 20]]])

In [14]:
a.shape

torch.Size([1, 1, 20])

In [15]:
a=a.squeeze()
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [16]:
a.shape

torch.Size([20])

In [17]:
b=torch.arange(1,21)
b

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [18]:
b=b.reshape(4,5)
b

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [19]:
b[0]

tensor([1, 2, 3, 4, 5])

In [20]:
b[1]

tensor([ 6,  7,  8,  9, 10])

In [21]:
b[2][4]

tensor(15)

In [22]:
b[2][4]

tensor(15)

In [23]:
b[3,2]

tensor(18)

In [24]:
#Numpy And tensor

In [25]:
array=np.arange(1,11)
tensor=torch.from_numpy(array)
print(array)
print(tensor)

[ 1  2  3  4  5  6  7  8  9 10]
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [26]:
array.dtype, tensor.dtype

(dtype('int64'), torch.int64)

In [27]:
#Random Seeding

In [28]:
Random_Seed=42

In [29]:
torch.manual_seed(Random_Seed)
tensor1=torch.rand(3,4)
tensor1

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [30]:
torch.manual_seed(Random_Seed)
tensor2=torch.rand(3,4)
tensor2

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [31]:
tensor1==tensor2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [32]:
#Acceccing GPU for faster computations with Cuda + Nvidia Hardware

In [33]:
import GPUtil

In [34]:
GPUtil.getAvailable()

[]

In [35]:
use_cuda = torch.cuda.is_available()
use_cuda

False

In [36]:
tensor=torch.tensor([1,2,3,4,5])
print(tensor, tensor.device)

tensor([1, 2, 3, 4, 5]) cpu


In [37]:
#Exercise

In [38]:
print(torch.cuda.is_available())

False


In [39]:
#Working on Torchvision dataset

In [40]:
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

In [41]:
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

In [42]:
print(training_data)

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()


In [43]:
print(test_data)

Dataset FashionMNIST
    Number of datapoints: 10000
    Root location: data
    Split: Test
    StandardTransform
Transform: ToTensor()
