In [1]:
import torch

In [2]:
torch.__version__

'2.6.0+cpu'

In [3]:
#Fundamentals of PyTorch

In [4]:
#Scalar

In [5]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.shape

torch.Size([])

In [8]:
#Vectors

In [9]:
vector=torch.tensor([1,2])

In [10]:
vector

tensor([1, 2])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
#matrix

In [14]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 3])

In [17]:
matrix[0]

tensor([1, 2, 3])

In [18]:
matrix[1]

tensor([4, 5, 6])

In [19]:
#Tensors of n-dimensions

In [20]:
tensor_3d = torch.tensor([[[1, 2, 3], [2, 3, 4]], 
                          [[5, 6, 7], [7, 8, 9]]])
tensor_3d

tensor([[[1, 2, 3],
         [2, 3, 4]],

        [[5, 6, 7],
         [7, 8, 9]]])

In [21]:
tensor_3d.shape

torch.Size([2, 2, 3])

In [22]:
tensor_3d.ndim

3

In [23]:
tensor_3d[0,1]

tensor([2, 3, 4])

In [24]:
tensor_3d[1,1]

tensor([7, 8, 9])

In [25]:
tensor_3d[1,1,2]

tensor(9)

In [26]:
#Random tensors

In [27]:
random_t=torch.rand(4,4,4)
random_t

tensor([[[0.7799, 0.5615, 0.0074, 0.8126],
         [0.3143, 0.0955, 0.0533, 0.8688],
         [0.5561, 0.6471, 0.9055, 0.6391],
         [0.6135, 0.3234, 0.8873, 0.8409]],

        [[0.7697, 0.1925, 0.2159, 0.2501],
         [0.0712, 0.8065, 0.0120, 0.4456],
         [0.4178, 0.4393, 0.3629, 0.3277],
         [0.0394, 0.2450, 0.6153, 0.5892]],

        [[0.8095, 0.2681, 0.6662, 0.6241],
         [0.0261, 0.3960, 0.9123, 0.1360],
         [0.2855, 0.5978, 0.1017, 0.6924],
         [0.0441, 0.6522, 0.0266, 0.9512]],

        [[0.0111, 0.5711, 0.3223, 0.9727],
         [0.6754, 0.0032, 0.5111, 0.2183],
         [0.7139, 0.1247, 0.5665, 0.0217],
         [0.6110, 0.0241, 0.7812, 0.9154]]])

In [28]:
random_t.shape

torch.Size([4, 4, 4])

In [29]:
random_t.ndim

3

In [30]:
#random size image

In [31]:
random_image_size_tensor = torch.rand(size=(144, 144, 3))
random_image_size_tensor.shape

torch.Size([144, 144, 3])

In [32]:
random_image_size_tensor.ndim

3

In [33]:
zeros=torch.zeros(3,4)

In [34]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
zeros.dtype

torch.float32

In [36]:
one=torch.ones(3,4)

In [37]:
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
one.dtype

torch.float32

In [39]:
torch.arange(4,25,2)

tensor([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [40]:
#data type 

In [41]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0316, 0.0676, 0.0243, 0.5247],
        [0.5203, 0.7955, 0.8452, 0.7207],
        [0.9814, 0.8438, 0.8298, 0.5274]])

In [42]:
print(f'size of the tensor : { some_tensor.dtype}')
print(f'size of the tensor : { some_tensor.shape}')
print(f'size of the tensor : { some_tensor.device}')

size of the tensor : torch.float32
size of the tensor : torch.Size([3, 4])
size of the tensor : cpu


In [43]:
#tensor_operation

In [44]:
tensorA=torch.tensor([2,4,9])

In [45]:
tensorA

tensor([2, 4, 9])

In [46]:
tensorA*5

tensor([10, 20, 45])

In [47]:
tensorA.add(5)

tensor([ 7,  9, 14])

In [48]:
tensorA.sub(10)

tensor([-8, -6, -1])

In [49]:
tensorA.div(5)

tensor([0.4000, 0.8000, 1.8000])

In [50]:
#Now Working On matrix

In [51]:
tensor_A=torch.tensor([[2,3],
                       [5,6],
                       [8,9]])

In [52]:
tensor_B=torch.tensor([[9,8],
                       [7,6],
                       [5,4]])

In [53]:
tensor_C=torch.tensor([[5,6,7],
                       [7,8,2]])

In [54]:
tensor_A.shape, tensor_B.shape, tensor_C.shape

(torch.Size([3, 2]), torch.Size([3, 2]), torch.Size([2, 3]))

In [55]:
tensor_A, tensor_B, tensor_C

(tensor([[2, 3],
         [5, 6],
         [8, 9]]),
 tensor([[9, 8],
         [7, 6],
         [5, 4]]),
 tensor([[5, 6, 7],
         [7, 8, 2]]))

In [56]:
torch.matmul(tensor_A, tensor_C)

tensor([[ 31,  36,  20],
        [ 67,  78,  47],
        [103, 120,  74]])

In [57]:
torch.matmul(tensor_A, tensor_B.T) #T is Transpose which chanege the dimension of the tensor

tensor([[ 42,  32,  22],
        [ 93,  71,  49],
        [144, 110,  76]])

In [58]:
#Tensor Aggregation

In [59]:
new_tensor=torch.arange(0,20,2)
new_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
torch.min(new_tensor)

tensor(0)

In [61]:
torch.max(new_tensor)

tensor(18)

In [62]:
torch.sum(new_tensor)

tensor(90)

In [63]:
print(type(new_tensor))

<class 'torch.Tensor'>


In [64]:
torch.mean(new_tensor.type(torch.float32))

tensor(9.)

In [65]:
torch.argmin(new_tensor)

tensor(0)

In [66]:
torch.argmax(new_tensor)

tensor(9)

In [67]:
#Reshaping

In [68]:
x=torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [69]:
y_reshape=x.reshape(10,1)
y_reshape

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [70]:
z_reshape=x.reshape(1,10)
z_reshape

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [71]:
z_reshape[:,5]

tensor([6])

In [72]:
z_reshape

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [73]:
a_reshape=x.reshape(2,5)
a_reshape

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [74]:
b_reshape=x.reshape(5,2)
b_reshape

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [75]:
#View

In [76]:
a=torch.arange(0,12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
b=a.view(1,12)
b

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [84]:
b[:,2]=25
b

tensor([[ 0,  1, 25,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [85]:
a

tensor([ 0,  1, 25,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [86]:
b

tensor([[ 0,  1, 25,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [87]:
b.T

tensor([[ 0],
        [ 1],
        [25],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])

In [88]:
b.reshape(3,4)

tensor([[ 0,  1, 25,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [90]:
c=torch.arange(0,12)
c

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
c_stack=torch.stack([c,c,c,c],dim=0)
c_stack

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [95]:
c_stack=torch.stack([c,c,c,c],dim=1)
c_stack

tensor([[ 0,  0,  0,  0],
        [ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10],
        [11, 11, 11, 11]])